services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: biblioteca1
      MYSQL_ROOT_PASSWORD: 2405
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DJANGO_SECRET_KEY: 'django-insecure-i9-0=d=djt-%fw$_cvl9^vkb2thns3p^t1(j9e1awr-9o7co&&'
      DEBUG: 'True'
      DATABASE_NAME: biblioteca1
      DATABASE_USER: root
      DATABASE_PASSWORD: 2405
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DJANGO_ALLOWED_HOSTS: 'localhost,127.0.0.1'
    depends_on:
      - db
    command: >
      sh -c "
      /app/wait-for-db.sh db &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

volumes:
  db_data:
