FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    libmariadb-dev \
    pkg-config \
    default-mysql-client \     
    && rm -rf /var/lib/apt/lists/*

# Copiar y preparar wait-for-db.sh
COPY wait-for-db.sh /app/wait-for-db.sh
RUN chmod +x /app/wait-for-db.sh

# Instalar dependencias de Python
COPY requirements.txt /app/requirements.txt
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Copiar el resto del código
COPY . /app

EXPOSE 8000

CMD ["sh", "-c", "/app/wait-for-db.sh db && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
